language: C
sudo: false
before_install:
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz
  - tar xzvf helm-v2.13.1-linux-amd64.tar.gz
  - mv linux-amd64/helm helm
  - chmod u+x helm
  - wget https://github.com/garethr/kubeval/releases/download/0.7.3/kubeval-linux-amd64.tar.gz 
  - tar xzvf kubeval-linux-amd64.tar.gz
  - chmod u+x kubeval
  - mv helm kubeval /home/travis/bin/
  - helm init -c
env:
  - KUBERNETES_VERSION="1.14.0"
jobs:
  include:
    - stage: lint chart syntax
      script:
        - echo $PATH
        - helm lint helm-chart/docker-mailserver
    - stage: kubeval generated manifests
      script:   
        - mkdir manifests
        - helm template helm-chart/docker-mailserver --output-dir manifests
        - find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBERNETES_VERSION
    - stage: execute unit tests
      script:  
        - mkdir helm-chart/docker-mailserver/config
        - echo "# ignore - used for unit testing" > helm-chart/docker-mailserver/config/postfix-main.cf
        - ls -la helm-chart/docker-mailserver/config/
        - helm plugin install https://github.com/lrills/helm-unittest
        - helm unittest helm-chart/docker-mailserver 
