language: C
sudo: false
before_install:
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v$HELM_VERSION-linux-amd64.tar.gz
  - tar xzvf helm-v$HELM_VERSION-linux-amd64.tar.gz
  - mv linux-amd64/helm helm
  - chmod u+x helm
  - wget https://github.com/garethr/kubeval/releases/download/$KUBEVAL_VERSION/kubeval-linux-amd64.tar.gz 
  - tar xzvf kubeval-linux-amd64.tar.gz
  - chmod u+x kubeval
env:
  - KUBERNETES_VERSION="1.14.0"
  - HELM_VERSION="2.13.1"  
  - KUBEVAL_VERSION="0.7.3"
jobs:
  include:
    - stage: helm-syntax
      script:
        - ./helm lint helm-chart/docker-mailserver
    - stage: kubectl-syntax
      script:   
        - mkdir manifests
        - ./helm template helm-chart/docker-mailserver --output-dir manifests
        - find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBERNETES_VERSION
    - stage: unit-tests
      script:  
        - ./helm plugin install https://github.com/lrills/helm-unittest
        - ./helm unittest helm-chart/docker-mailserver 
