branches:
  except:
    - donttestme

language: bash

sudo: required

env:
  global:
    - HADOLINT_VERSION=1.17.1
    - SHELLCHECK_VERSION=0.7.1

addons:
  apt:
    packages:
    - xz-utils

services:
  - docker

before_install:
  - sudo curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
  - sudo chmod +rx /usr/local/bin/hadolint
  - sudo wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv
  - sudo cp "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" /usr/bin/

install:
  - make lint
  - travis_retry travis_wait make build

script:
  - make shellcheck
  - make generate-accounts run generate-accounts-after-run fixtures tests

after_script:
  - make clean

notifications:
  slack:
    secure: TTo1z9nbZCWcIdfPwypubNa3y+pwvfgDGlzEVAGEuK7uuIpmEoAcAUNSSPTnbewDGHnDl8t/ml93MtvP+a+IVuAKytMqF39PHyoZO7aUl9J62V+G75OmnyGjXGJm40pQosCS6LzqoRRYXotl9+fwH568Kf4ifXCrMZX1d+ir7Ww=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7ec65291bfb4bf1f8518
    on_success: always
    on_failure: always
    on_start: never
