name: Bug Report
description: File a bug report
title: "[BUG] "
labels:
  - kind/bug
  - meta/needs triage
  - priority/medium

body:
  - type: markdown
    attributes:
      value: |
        Thank you for participating in this project and reporting a bug. Docker Mail Server (DMS) is a community-driven project, and each contribution counts.

        Please **fill out all the fields and checkboxes of this form** to make it easier for maintainers to understand the problem and to solve it. If this template is not adhered to, it will be marked with a label called `meta/no template - no support` and will not be worked on.

        **Make sure** you read through the whole README, the documentation and the issue tracker before opening a new bug report.
  - type: input
    id: affected-components
    attributes:
      label: Affected Component(s)
      description: What is affected by this bug? Please describe it with only a few words here. Detailed description can be given later.
      placeholder: No debug output is shown.
    validations:
      required: true
  - type: textarea
    id: when-does-it-occur
    attributes:
      label:  When does this occur and what happened?
      description: Tell us what happened. Use [fenced code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) when pasting lots of text!
      placeholder: Although `DMS_DEBUG=1` is set, I see no debug.
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect-to-happen
    attributes:
      label:  What did you expect to happen?
      description: Tell us what you expected.
      placeholder: I expected to see debug messages.
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: how-do-we-replicate-this-issue
    attributes:
      label: How do we replicate the issue?
      description: What did you do and how can we replicate this issue?
      value: |
        1.
        2.
        3.
        ...
      render: Markdown
    validations:
      required: true
  - type: input
    id: mailserver-version
    attributes:
      label: Mail server version
      description: What version are you running? Paste your image tag here.
      placeholder: v10.1.2
    validations:
      required: true
  - type: dropdown
    id: main-memory
    attributes:
      label: How much RAM is available?
      description: Please tell us how much main memory is available for DMS.
      options:
        - <= 1GB
        - <= 2GB
        - <= 4GB
        - \> 4GB
    validations:
      required: true
  - type: dropdown
    id: cpu-count
    attributes:
      label: How many CPU cores are available?
      description: Please tell us how many CPU cores are available for DMS. A vCore is a CPU core used in virtual machines, a physical core is a real CPU core.
      options:
        - 1 vCore
        - 2 vCores
        - 4 vCores
        - \> 4 vCores
        - 1 physical Core
        - 2 physical Cores
        - 4 physical Cores
        - \> 4 physical Cores
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system is DMS running on?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: dropdown
    id: isa
    attributes:
      label: What instruction set architecture is DMS running on?
      options:
        - x86_64 / AMD64
        - ARM v7
        - ARM64
    validations:
      required: true
  - type: dropdown
    id: container-orchestrator
    attributes:
      label: What container orchestration tool are you using?
      options:
        - Docker
        - Docker Compose
        - Podman
        - Kubernetes
        - Something else
    validations:
      required: true
  - type: input
    id: docker-version
    attributes:
      label: Docker version
      description: Please show us the output of `docker --version` on the host your mail server is running on if you are using Docker. Note that if you are not using Docker, there is no official support provided by maintainers as DMS mainly focuses on Docker (and Docker Compose).
      placeholder: Docker version 20.10.7, build f0df350
    validations:
      required: false
  - type: input
    id: docker-compose-version
    attributes:
      label: Docker compose version
      description: Please show us the output of `docker-compose --version` on the host your mail server is running on. Note that if you are not using Docker Compose, there is no official support provided by maintainers as DMS mainly focuses on Docker COmpose (and Docker).
      placeholder: docker-compose version 1.28.6, build 5db8d86f
    validations:
      required: false
  - type: input
    id: uname-a
    attributes:
      label: The output of `uname -a`
      description: Please paste the output of `uname -a` here.
      placeholder: Linux swift 5.11.0-31-generic \#33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
    validations:
      required: true
  - type: textarea
    id: important-environment-variables
    attributes:
      label: Important environment variables
      description: If there are environment variables important to this issue, please post them here. If we ask for the values of variables, make sure to put them in here too.
      render: bash
  - type: textarea
    id: relevant-log-output
    attributes:
      label: Relevant log output
      description: Show us relevant log output here. You can enable debug output by setting `DMS_DEBUG` to `1`.
      render: shell
  - type: textarea
    id: other-relevant-information
    attributes:
      label: Other relevant information
      description: If there is more, you can tell us here. Make sure to use Markdown formatting here.
      render: Markdown
  - type: dropdown
    id: experience
    attributes:
      label: What level of experience do you have with Docker and mail servers?
      description: You are not obliged to answer this question. But answering it helps us better understand where possible causes of errors lie. Less experienced users are more likely do make "obvious" mistakes, which is fine, and by answering this question, we know to look for them as well. We encourage everyone to participate, regardless of their level of experience.
      options:
        - I'm very much a beginner
        - I'm a novice
        - I know containerization but have less experience with mail
        - I have experience with mail but less experience with containerization
        - I know both pretty well and I'm experienced
        - I'm an expert
        - Trust me, I'm a (computer) engineer
    validations:
      required: false
  - type: checkboxes
    id: terms-code-of-conduct
    attributes:
      label: Code of conduct
      description: By submitting this issue, you agree to follow [our code of conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I read this project's Code of Conduct and I agree
          required: true
        - label: I read the README and the documentation but could not find a solution
          required: true
  - type: checkboxes
    id: terms-miscellaneous
    attributes:
      label: Miscellaneous
      description: Please read these carefully and check the appropriate boxes.
      options:
        - label: I checked that all ports are open and not blocked by my ISP / hoster.
          required: true
        - label: Just to make sure you're not just clicking checkboxes, please do not check this checkbox.
          required: false
        - label: I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
          required: true
