---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}
data:
  postfix-accounts.cf: "hello"
  postfix-virtual.cf: "hello"
  SigningTable: "hello"
  KeyTable: "hello"
  TrustedHosts: "hello"
  # example.property.file: |-
  #   property.1=value-1
  #   property.2=value-2
