---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}-configs
data:
  {{/* Use sample data if user is running in demo mode */}}
  {{- if .Values.demo_mode.enabled -}}  
  ### We are in demo mode, so add in some sample data for quick testing
  postfix-accounts.cf: |
    # A sample user - the password is "password"
    user@example.com|{SHA512-CRYPT}$6$l4023rZnQEy/l0Rg$JeNjAAICB43VAX7GTJ9jeE7DR0LeyR5nU.ftq3c42T5E1IZSuRBqwM8erRh6t0CyIT6aYpBIAopzcQHNUvMV00
  postfix-virtual.cf:
  SigningTable: "*@example.com mail._domainkey.example.com"
  KeyTable: "mail._domainkey.example.com example.com:mail:/etc/opendkim/keys/example.com/mail.private"
  TrustedHosts: |
    127.0.0.1
    localhost
  ### End demo mode data
  {{/* Use real data from "config" subdirectory if user is _not_ running in demo mode */}}  
  {{ else -}}
  {{- (.Files.Glob "config/*").AsConfig | nindent 2 }}
  {{- end }}
  {{/* Enable proxy protocol for postscreen / dovecot */}}
  {{ if .Values.haproxy.enabled -}} 
  postfix-main.cf: |
    # Necessary to permit proxy protocol from haproxy to postscreen
    postscreen_upstream_proxy_protocol = haproxy
  {{ end }}
  {{ if .Values.haproxy.enabled -}}  
  dovecot.cf: |   
    service imap-login {
      inet_listener imap {
        haproxy = yes
      }      
    }  
  {{ end }}
