---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}-secrets
data:
  webhook_token.secret: {{ .Files.Get "webhook_token.secret" | b64enc | quote}}
  bar: {{ .Values.Bar | b64enc | quote }}
  # opendkim-keys: {{ .Values.Bar | b64enc | quote }}
