name: "Build, Test & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'target/**'
      - '.dockerignore'
      - '.gitmodules'
      - 'Dockerfile'
      - 'setup.sh'
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-test-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare tags
        id: prep
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            ${{ secrets.DOCKER_REPOSITORY }}
            ${{ secrets.GHCR_REPOSITORY }}
          tags: |
            type=raw,value=edge

      - name: Build image
        uses: ./github/workflows/generic_build.yml
        with:
          platforms: linux/amd64
          publish: false
          cache-layers-to: true

      - name: Run test suite
        run: >
          NAME=mailserver-testing:ci
          bash -c 'make generate-accounts tests'
        env:
          CI: true

  build-multiarch-and-publish:
    needs: build-and-test-image
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare tags
        id: prep
        uses: docker/metadata-action@v4.0.1
        with:
          images: |
            ${{ secrets.DOCKER_REPOSITORY }}
            ${{ secrets.GHCR_REPOSITORY }}
          tags: |
            type=edge,branch=master
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
          flavor: |
            latest=auto

      - name: Build image
        uses: ./github/workflows/generic_build.yml
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          publish: true
          cache-layers-from: true
