name: Test the DMS Container Image

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

permissions:
  contents: read

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Required to retrieve bats (core + extras):
          submodules: recursive

      # Get the cached build layers from a build job:
      # This should always be a cache-hit, no new uploads
      # should happen when this job finishes:
      - name: Retrieve image build from build cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: cache-buildx-${{ inputs.cache-key }}
          restore-keys: |
            cache-buildx-

      # Importing from the cache should create the image
      # within approx 30 seconds:
      # buildx not needed as no exporting and only single
      # AMD64 platform is loaded:
      - name: Build AMD64 image from cache
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VER=${{ github.ref }}
          tags: mailserver-testing:ci
          # Export the built image for the Docker host to use:
          load: true
          # Rebuilds the AMD64 image from the cache:
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Run tests
        run: >
          NAME=mailserver-testing:ci
          make generate-accounts tests
        env:
          CI: true
