name: 'Documentation'

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-20.04
    env:
      PREVIEW_PREFIX: pullrequest-${{ github.event.pull_request.number }}
      SITE_NAME: dms-doc-previews
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs
        run: |
          # Adjust mkdocs.yml for preview build
          sed -i "s|^site_url:.*|site_url: 'https://${PREVIEW_PREFIX}--${SITE_NAME}.netlify.app/'|" mkdocs.yml

          docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material:7.1.3 build --strict
