name: Build Edge on Schedule

on:
  schedule:
    - cron: 0 0 * * 5

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    name: Build the container images
    uses: ./github/workflows/generic_build.yml
    with:
      extra-platforms: ',linux/arm/v7,linux/arm64'

  publish-images:
    name: Publish the container images
    needs: build-images
    uses: ./github/workflows/generic_publish.yml
    with:
      cache-key: ${{ needs.build-images.outputs.build-cache-key }}
