name: Build Edge on Schedule

on:
  schedule:
    - cron: 0 0 * * 5

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./github/workflows/generic_build.yml
    with:
      platforms: linux/amd64,linux/arm/v7,linux/arm64
      publish: true
