name: 'Test Merge Requests'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - target/**
      - test/**
      - .dockerignore
      - .gitmodules
      - Dockerfile
      - setup.sh

permissions:
  contents: read

jobs:
  build-image-amd64:
    name: 'Build AMD64 Image'
    uses: ./.github/workflows/generic_build.yml

  run-tests:
    name: 'Test AMD64 Image'
    needs: build-image-amd64
    uses: ./.github/workflows/generic_test.yml
    with:
      cache-key: ${{ needs.build-image-amd64.outputs.build-cache-key }}

  job-build-arm:
    name: 'Build ARM64 Image'
    # Dependency ensures the cache-key is only created for AMD64 builds.
    # ARM64 will not be able to use this cache, building from scratch each time.
    # Expect about 13 minutes build time until adopting `type=gha` with scopes for cache.
    needs: build-image-amd64
    uses: ./.github/workflows/generic_build.yml
    with:
      extra-platforms: ',linux/arm64'
