name: Test Merge Requests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - target/**
      - test/**
      - .dockerignore
      - .gitmodules
      - Dockerfile
      - setup.sh

permissions:
  contents: read

jobs:
  build-AMD64-image:
    name: Build AMD64 Image
    uses: ./.github/workflows/generic_build.yml

  run-tests:
    name: Test AMD64 Image
    needs: build-AMD64-image
    uses: ./.github/workflows/generic_test.yml
    with:
      cache-key: ${{ needs.build-AMD64-image.outputs.build-cache-key }}

  job-build-arm:
    name: Build ARM64 Image
    uses: ./.github/workflows/generic_build.yml
    with:
      extra-platforms: ',linux/arm64'
