name: "Test Merge Requests"

on: 
  pull_request:
    paths: 
      - 'target/**'
      - 'test/**'
      - '.dockerignore'
      - '.gitmodules'
      - 'Dockerfile'
      - 'setup.sh'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
        id: buildx
      - name: Build image locally
        uses: docker/build-push-action@v2.4.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VER=${{ github.ref }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: false
          load: true
          tags: mailserver-testing:ci
      - name: Run test suite
        run: >
          NAME=mailserver-testing:ci
          bash -c 'make generate-accounts tests'
        env:
          CI: true
